### ISSUE TITLE
Problem with launching the application - Build (16/17)

### ISSUE THREAD

**Issue by tarzinio** [Daniel31x13/link-warden#17]
I have a problem launching the application. I downloaded the applications and ran the command (`docker compose up -d`).
The app has stopped on trial 16/17 and is still standing there. I attach a screen

![Screenshot_1](https://user-images.githubusercontent.com/29274594/184125669-aeb04a9a-a89f-47e3-800e-168f0f2befa6.png)

does anyone know what the problem is? I would like to add that all this time it consumes ~ 100% of my vps resources

![Screenshot_2](https://user-images.githubusercontent.com/29274594/184126024-e4a84f97-6442-4189-bbf8-19064888a56b.png)

**Comment by AlienPie** [comment]
The docker compose script builds the docker image. This means that it must compile the code first. I also got this warning but the build completed and deployed as expected. It's just a warning as far as I can tell.

The high CPU usage is due to the code building. Given your load average I would say it's just struggling to compile and taking its time.
